---
permalink: api/reference_element_api_getcompletestats.html 
sidebar: sidebar 
keywords:  
summary: 'L"ingénierie NetApp teste les nouvelles fonctionnalités à l"aide de la méthode GetCompleteStats (API GetCompleteStats). Les données renvoyées par GetCompleteStats ne sont pas documentées, changent fréquemment et ne sont pas garanties d"être précises. Nous ne recommandons pas d"utiliser GetCompleteStats pour collecter des données de performances ou toute autre intégration de la gestion avec un cluster de stockage exécutant le logiciel Element.' 
---
= GetCompleteStats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'ingénierie NetApp utilise `GetCompleteStats` la méthode API pour tester de nouvelles fonctionnalités. Les données renvoyées par `GetCompleteStats` ne sont pas documentées, changent fréquemment et ne sont pas garanties d'être exactes. Vous ne devez pas utiliser `GetCompleteStats` pour collecter des données de performances ou toute autre intégration de gestion à un cluster de stockage exécutant le logiciel Element.

Utilisez les méthodes API suivantes prises en charge pour récupérer des informations statistiques :

* xref:reference_element_api_getvolumestats.adoc[GetVolumeStats]
* xref:reference_element_api_getclusterstats.adoc[GetClusterStats]
* xref:reference_element_api_getnodestats.adoc[GetNodeStats]
* xref:reference_element_api_getdrivestats.adoc[GetDriveStats]




== Nouveau depuis la version

9,6
